apiVersion: v1
kind: Service
metadata:
  name: regex-app-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001  # You can change this port
  selector:
    app: regex-app
